ort:
  enableRepositoryPackageConfigurations: true
  enableRepositoryPackageCurations: true
  forceOverwrite: true
  licenseFactProviders:
    SPDX: {}
    ScanCode: {}
    DefaultDir: {}

  licenseFilePatterns:
    licenseFilenames: ['license*']
    noticeFilenames: ['notice*']
    patentFilenames: ['patents']
    otherLicenseFilenames: ['readme*']

  packageConfigurationProviders:
  - type: DefaultDir
  - type: OrtConfig

  # Package curation providers are listed from highest to lowest priority. Technically, they are applied in reverse
  # order: The provider with the highest priority is applied last, so it can overwrite any previously applied curations.
  packageCurationProviders:
  - type: DefaultFile
  - type: DefaultDir
  - type: ClearlyDefined
    options:
      serverUrl: 'https://api.clearlydefined.io'
      minTotalLicenseScore: 80

  severeIssueThreshold: ERROR
  severeRuleViolationThreshold: ERROR

  analyzer:
    allowDynamicVersions: true

  downloader:
    allowMovingRevisions: true
    skipExcluded: true
  scanner:
    skipConcluded: true
    skipExcluded: true
    archive:
      enabled: true
      fileStorage:
        localFileStorage:
          directory: ~/.ort/scanner/archive
          compression: false

    fileListStorage:
      fileStorage:
        localFileStorage:
          directory: ~/.ort/scanner/file-lists
          compression: false
    
    storageReaders: [fileBasedStorage, clearlyDefined]

    provenanceStorage:
      fileStorage:
        localFileStorage:
          directory: ~/.ort/scanner/provenance
          compression: false

  reporter:
    config:
      CycloneDx:
        options:
          schema.version: 1.6
